### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by nagibmahfuj** [philipshurpik/react-native-starter-kit#4]
Your starter is really great but it is not working with latest updates of React and others packages. Please try to update @philipshurpik ...

**Comment by nagibmahfuj** [comment]
Update: I have managed to migrate myself..

**Comment by philipshurpik** [comment]
Hi!  Thanks )
I finally decided to update everything with router and some code practices to be more relevant :)
So welcome to use

**Comment by nagibmahfuj** [comment]
Thanks for the update.. Though I did too already. :)
